# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  imageName: 'pipelines-javascript-docker'
  DOCKER_BUILDKIT: 1

steps:
- script: pwd
  displayName: 'Print pwd'

- script: |
    echo 'Install task and run task ci'
    sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b ~/.local/bin
    echo $PATH
    export PATH=${PATH}:~/.local/bin

  displayName: 'install task and run task ci'

- script: task ci
  displayName: 'task ci'