# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, Welcome to SDinc ( Specialty Diagnostics Incorporated )
  SDINC_TF_VERSION: "hashicorp/terraform:1.5.2"
  SDINC_TF_DOCKER_OPTIONS: "-i -t -v ${HOME}/.aws:/root/.aws -v ${HOME}/.azure:/root/.azure -v ${HOME}/.terraform.d:/root/.terraform.d -v $(pwd):$(pwd) -w $(pwd)"
  SDINC_AZ_VERSION: "mcr.microsoft.com/azure-cli:2.51.0-arm64"
  SDINC_AZ_DOCKER_OPTIONS: "-i -t -v ${HOME}/.azure:/root/.azure -v $(pwd):$(pwd) -w $(pwd)"
  SDINC_AWS_VERSION: "public.ecr.aws/aws-cli/aws-cli:2.13.18"
  SDINC_AWS_LATEST: "public.ecr.aws/aws-cli/aws-cli:latest"
  SDINC_AWS_DOCKER_OPTIONS: "-i -t -v ${HOME}/.aws:/root/.aws -v $(pwd):$(pwd) -w $(pwd)"
  SDINC_LATEST: "sdinc:latest"
  EPOCH:
    sh: date +%s
tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
      - task --list
      - date -u
    silent: true
  tf-init:
    desc: "terraform init via docker backend terraform cloud"
    cmds:
      - "docker run {{.SDINC_TF_DOCKER_OPTIONS}} {{.SDINC_TF_VERSION}} init"
  tf-login:
    desc: "terraform login via docker backend terraform cloud"
    cmds:
      - "docker run {{.SDINC_TF_DOCKER_OPTIONS}} {{.SDINC_TF_VERSION}} login"
  tf-plan:
    desc: "terraform plan via docker backend terraform cloud"
    cmds:
      - "docker run {{.SDINC_TF_DOCKER_OPTIONS}} {{.SDINC_TF_VERSION}} plan"
  tf-apply:
    desc: "terraform apply via docker backend terraform cloud"
    cmds:
      - "docker run {{.SDINC_TF_DOCKER_OPTIONS}} {{.SDINC_TF_VERSION}} apply"
  aws-who:
    desc: "aws sts get-caller-identity"
    cmds:
      - "docker run {{.SDINC_AWS_DOCKER_OPTIONS}} {{.SDINC_AWS_VERSION}} sts get-caller-identity"
  aws-build:
    desc: "build a aws container with bash shell"
    cmds:
      - "docker build -t {{.SDINC_LATEST}} ."
  aws-cli:
    desc: "aws sts get-caller-identity"
    cmds:
      - 'docker run --entrypoint="/bin/bash" {{.SDINC_AWS_DOCKER_OPTIONS}} {{.SDINC_LATEST}} '
  checkov:
    desc: "run checkov via docker"
    cmds:
      - "docker run {{.SDINC_AWS_DOCKER_OPTIONS}}  bridgecrew/checkov --directory $(pwd) "
  az-cli:
    cmds:
      - "docker run {{.SDINC_AZ_DOCKER_OPTIONS}} {{.SDINC_AZ_VERSION}} "