/* Form definition file generated with fdesign. */

#include "forms.h"
#include <stdlib.h>
#include "final_gui.h"

FD_final *create_form_final(void)
{
  FL_OBJECT *obj;
  FD_final *fdui = (FD_final *) fl_calloc(1, sizeof(*fdui));

  fdui->final = fl_bgn_form(FL_NO_BOX, 580, 560);
  obj = fl_add_box(FL_UP_BOX,0,0,580,560,"");
    fl_set_object_color(obj,FL_RIGHT_BCOL,FL_COL1);
    fl_set_object_lcolor(obj,FL_WHITE);
  obj = fl_add_labelframe(FL_ENGRAVED_FRAME,230,230,220,320,"Camera Orientation");
    fl_set_object_color(obj,FL_LIGHTER_COL1,FL_RIGHT_BCOL);
    fl_set_object_lcolor(obj,FL_WHITE);
    fl_set_object_lsize(obj,FL_MEDIUM_SIZE);
  obj = fl_add_button(FL_INOUT_BUTTON,290,10,270,40,"Start Skater");
    fl_set_object_boxtype(obj,FL_ROUNDED3D_UPBOX);
    fl_set_object_color(obj,FL_BLUE,FL_COL1);
    fl_set_object_lcolor(obj,FL_WHITE);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_TIMESBOLD_STYLE);
    fl_set_object_callback(obj,start_skater_cb,0);
  obj = fl_add_button(FL_INOUT_BUTTON,290,60,270,40,"Exit Program");
    fl_set_object_boxtype(obj,FL_ROUNDED3D_UPBOX);
    fl_set_object_color(obj,FL_BLUE,FL_COL1);
    fl_set_object_lcolor(obj,FL_WHITE);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_TIMESBOLD_STYLE);
    fl_set_object_callback(obj,exit_program_cb,0);
  fdui->xcamera = obj = fl_add_valslider(FL_VERT_BROWSER_SLIDER,270,240,30,290,"X Camera");
    fl_set_object_color(obj,FL_BLUE,FL_RIGHT_BCOL);
    fl_set_object_lcolor(obj,FL_WHITE);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_callback(obj,eye_cb,0);
    fl_set_slider_precision(obj, 1);
    fl_set_slider_bounds(obj, 500, -500);
    fl_set_slider_value(obj, 0);
    fl_set_slider_step(obj, 1);
  fdui->ycamera = obj = fl_add_valslider(FL_VERT_BROWSER_SLIDER,330,240,30,290,"Y Camera");
    fl_set_object_color(obj,FL_BLUE,FL_RIGHT_BCOL);
    fl_set_object_lcolor(obj,FL_WHITE);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_callback(obj,eye_cb,1);
    fl_set_slider_precision(obj, 1);
    fl_set_slider_bounds(obj, 500, -500);
    fl_set_slider_value(obj, 0);
    fl_set_slider_step(obj, 1);
  fdui->zcamera = obj = fl_add_valslider(FL_VERT_BROWSER_SLIDER,400,240,30,290,"Z Camera");
    fl_set_object_color(obj,FL_BLUE,FL_RIGHT_BCOL);
    fl_set_object_lcolor(obj,FL_WHITE);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_callback(obj,eye_cb,2);
    fl_set_slider_precision(obj, 1);
    fl_set_slider_bounds(obj, 500, -500);
    fl_set_slider_value(obj, 0);
    fl_set_slider_step(obj, 1);
     fl_set_slider_return(obj, FL_RETURN_ALWAYS);
  obj = fl_add_labelframe(FL_ENGRAVED_FRAME,20,30,200,340,"Manuvers");
    fl_set_object_color(obj,FL_LIGHTER_COL1,FL_RIGHT_BCOL);
    fl_set_object_lcolor(obj,FL_WHITE);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
  obj = fl_add_labelframe(FL_ENGRAVED_FRAME,330,110,210,110,"Lights");
    fl_set_object_color(obj,FL_WHITE,FL_RIGHT_BCOL);
    fl_set_object_lcolor(obj,FL_WHITE);
  obj = fl_add_checkbutton(FL_PUSH_BUTTON,340,130,40,40,"Ambient Light");
    fl_set_object_color(obj,FL_BLUE,FL_WHITE);
    fl_set_object_lcolor(obj,FL_WHITE);
    fl_set_object_lalign(obj,FL_ALIGN_TOP);
    fl_set_object_callback(obj,Light_cb,0);
    fl_set_button(obj, 1);
  obj = fl_add_checkbutton(FL_PUSH_BUTTON,420,130,40,40,"Yellow Spot");
    fl_set_object_color(obj,FL_BLUE,FL_WHITE);
    fl_set_object_lcolor(obj,FL_WHITE);
    fl_set_object_lalign(obj,FL_ALIGN_TOP);
    fl_set_object_callback(obj,Light_cb,1);
    fl_set_button(obj, 1);
  obj = fl_add_checkbutton(FL_PUSH_BUTTON,470,130,40,40,"Cyan P ");
    fl_set_object_color(obj,FL_BLUE,FL_WHITE);
    fl_set_object_lcolor(obj,FL_WHITE);
    fl_set_object_lalign(obj,FL_ALIGN_TOP);
    fl_set_object_callback(obj,Light_cb,2);
    fl_set_button(obj, 1);
  obj = fl_add_checkbutton(FL_PUSH_BUTTON,420,180,40,40,"Red Light ");
    fl_set_object_color(obj,FL_BLUE,FL_WHITE);
    fl_set_object_lcolor(obj,FL_WHITE);
    fl_set_object_lalign(obj,FL_ALIGN_TOP);
    fl_set_object_callback(obj,Light_cb,3);
    fl_set_button(obj, 1);
  obj = fl_add_checkbutton(FL_PUSH_BUTTON,470,180,40,40,"White D");
    fl_set_object_color(obj,FL_BLUE,FL_WHITE);
    fl_set_object_lcolor(obj,FL_WHITE);
    fl_set_object_lalign(obj,FL_ALIGN_TOP);
    fl_set_object_callback(obj,Light_cb,4);
    fl_set_button(obj, 1);
  obj = fl_add_checkbutton(FL_PUSH_BUTTON,340,180,40,40,"Light Objects");
    fl_set_object_color(obj,FL_BLUE,FL_WHITE);
    fl_set_object_lcolor(obj,FL_WHITE);
    fl_set_object_lalign(obj,FL_ALIGN_TOP);
    fl_set_object_callback(obj,Light_cb,5);
  obj = fl_add_button(FL_NORMAL_BUTTON,60,50,100,50,"Varial");
    fl_set_object_color(obj,FL_BLUE,FL_COL1);
    fl_set_object_lcolor(obj,FL_WHITE);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_FIXEDBOLDITALIC_STYLE);
    fl_set_object_callback(obj,Manuver_cb,0);
  obj = fl_add_button(FL_NORMAL_BUTTON,60,110,100,50,"Kick Flip");
    fl_set_object_color(obj,FL_BLUE,FL_COL1);
    fl_set_object_lcolor(obj,FL_WHITE);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_FIXEDBOLDITALIC_STYLE);
    fl_set_object_callback(obj,Manuver_cb,1);
  obj = fl_add_button(FL_NORMAL_BUTTON,60,170,100,50,"Flip");
    fl_set_object_color(obj,FL_BLUE,FL_COL1);
    fl_set_object_lcolor(obj,FL_WHITE);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_FIXEDBOLDITALIC_STYLE);
    fl_set_object_callback(obj,Manuver_cb,2);
  obj = fl_add_button(FL_NORMAL_BUTTON,60,230,100,50,"360");
    fl_set_object_color(obj,FL_BLUE,FL_COL1);
    fl_set_object_lcolor(obj,FL_WHITE);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_FIXEDBOLDITALIC_STYLE);
    fl_set_object_callback(obj,Manuver_cb,3);
  obj = fl_add_button(FL_NORMAL_BUTTON,60,290,100,50,"Ollie");
    fl_set_object_color(obj,FL_BLUE,FL_COL1);
    fl_set_object_lcolor(obj,FL_WHITE);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_lstyle(obj,FL_FIXEDBOLDITALIC_STYLE);
    fl_set_object_callback(obj,Manuver_cb,4);
  obj = fl_add_labelframe(FL_ENGRAVED_FRAME,20,400,160,140,"Freeze rotates");
    fl_set_object_color(obj,FL_LIGHTER_COL1,FL_RIGHT_BCOL);
    fl_set_object_lcolor(obj,FL_WHITE);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
  fdui->frez_x = obj = fl_add_valslider(FL_VERT_BROWSER_SLIDER,30,420,30,100,"X");
    fl_set_object_color(obj,FL_BLUE,FL_RIGHT_BCOL);
    fl_set_object_lcolor(obj,FL_WHITE);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_callback(obj,freeze_cb,0);
    fl_set_slider_precision(obj, 1);
    fl_set_slider_bounds(obj, 180, -180);
    fl_set_slider_value(obj, 0);
    fl_set_slider_step(obj, 1);
  fdui->frez_y = obj = fl_add_valslider(FL_VERT_BROWSER_SLIDER,80,420,30,100,"Y");
    fl_set_object_color(obj,FL_BLUE,FL_RIGHT_BCOL);
    fl_set_object_lcolor(obj,FL_WHITE);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_callback(obj,freeze_cb,1);
    fl_set_slider_precision(obj, 1);
    fl_set_slider_bounds(obj, 180, -180);
    fl_set_slider_value(obj, 0);
    fl_set_slider_step(obj, 1);
  fdui->frez_z = obj = fl_add_valslider(FL_VERT_BROWSER_SLIDER,130,420,30,100,"Z");
    fl_set_object_color(obj,FL_BLUE,FL_RIGHT_BCOL);
    fl_set_object_lcolor(obj,FL_WHITE);
    fl_set_object_lsize(obj,FL_NORMAL_SIZE);
    fl_set_object_callback(obj,freeze_cb,2);
    fl_set_slider_precision(obj, 1);
    fl_set_slider_bounds(obj, 180, -180);
    fl_set_slider_value(obj, 0);
    fl_set_slider_step(obj, 1);
  fl_end_form();

  fdui->final->fdui = fdui;

  return fdui;
}
/*---------------------------------------*/

